-- ================================================================
-- DisasterEye — Script Oracle Database
-- Disciplina: C# Development · FIAP · Turma: 3ESPR
-- Executar como: DBA ou usuário com privilégios DDL
-- ================================================================

-- ── Limpeza (ordem respeita FKs) ────────────────────────────────
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TECNOLOGIAS CASCADE CONSTRAINTS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIOS CASCADE CONSTRAINTS';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CATEGORIASIMPACTO CASCADE CONSTRAINTS';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "EFMIGRATIONSHISTORY" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ── Tabelas ──────────────────────────────────────────────────────

CREATE TABLE CATEGORIASIMPACTO (
    ID           NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME         VARCHAR2(100)  NOT NULL,
    DESCRICAO    VARCHAR2(500)  DEFAULT '' NOT NULL,
    TIPODESASTRE VARCHAR2(100)  DEFAULT '' NOT NULL
);

CREATE TABLE USUARIOS (
    ID           NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME         VARCHAR2(100)  NOT NULL,
    EMAIL        VARCHAR2(200)  NOT NULL,
    SENHAHASH    VARCHAR2(255)  NOT NULL,
    PERFIL       VARCHAR2(50)   DEFAULT 'Pesquisador' NOT NULL,
    DATACADASTRO TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    ATIVO        NUMBER(1)      DEFAULT 1 NOT NULL,
    CONSTRAINT UQ_USUARIOS_EMAIL  UNIQUE (EMAIL),
    CONSTRAINT CK_USUARIOS_ATIVO  CHECK (ATIVO IN (0,1)),
    CONSTRAINT CK_USUARIOS_PERFIL CHECK (PERFIL IN ('Administrador','Pesquisador'))
);

CREATE TABLE TECNOLOGIAS (
    ID                 NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME               VARCHAR2(200)   NOT NULL,
    DESCRICAO          VARCHAR2(1000)  DEFAULT '' NOT NULL,
    ORIGEMESPACIAL     VARCHAR2(200)   DEFAULT '' NOT NULL,
    LATITUDE           BINARY_DOUBLE   NULL,
    LONGITUDE          BINARY_DOUBLE   NULL,
    STATUS             VARCHAR2(50)    DEFAULT 'Ativo' NOT NULL,
    DATACADASTRO       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CATEGORIAIMPACTOID NUMBER          NOT NULL,
    CONSTRAINT FK_TEC_CATEGORIA FOREIGN KEY (CATEGORIAIMPACTOID)
        REFERENCES CATEGORIASIMPACTO(ID),
    CONSTRAINT CK_TEC_STATUS CHECK (STATUS IN ('Ativo','Monitorando','Alerta','Crítico'))
);

CREATE TABLE "EFMIGRATIONSHISTORY" (
    "MigrationId"    VARCHAR2(150) NOT NULL,
    "ProductVersion" VARCHAR2(32)  NOT NULL,
    CONSTRAINT PK_EFMigHist PRIMARY KEY ("MigrationId")
);

-- ── Índices ──────────────────────────────────────────────────────
CREATE INDEX IDX_TEC_CATEGORIA   ON TECNOLOGIAS (CATEGORIAIMPACTOID);
CREATE INDEX IDX_TEC_STATUS      ON TECNOLOGIAS (STATUS);
CREATE INDEX IDX_TEC_DATACAD     ON TECNOLOGIAS (DATACADASTRO DESC);
CREATE INDEX IDX_USU_EMAIL       ON USUARIOS (EMAIL);

-- ── Seed: Categorias ─────────────────────────────────────────────
INSERT INTO CATEGORIASIMPACTO (NOME, DESCRICAO, TIPODESASTRE) VALUES ('Incêndios Florestais','Monitoramento de incêndios via satélite','Wildfires');
INSERT INTO CATEGORIASIMPACTO (NOME, DESCRICAO, TIPODESASTRE) VALUES ('Inundações','Detecção de cheias e alagamentos','Floods');
INSERT INTO CATEGORIASIMPACTO (NOME, DESCRICAO, TIPODESASTRE) VALUES ('Terremotos','Análise sísmica via sensores espaciais','Earthquakes');
INSERT INTO CATEGORIASIMPACTO (NOME, DESCRICAO, TIPODESASTRE) VALUES ('Vulcões','Monitoramento de atividade vulcânica','Volcanoes');
INSERT INTO CATEGORIASIMPACTO (NOME, DESCRICAO, TIPODESASTRE) VALUES ('Tempestades Severas','Rastreamento de furacões e tempestades','Severe Storms');

-- ── Seed: Admin (senha hasheada pelo EF Core na primeira migration) ─
-- Para testar sem o EF, gere o hash via: BCrypt.HashPassword("Admin@123")
INSERT INTO USUARIOS (NOME, EMAIL, SENHAHASH, PERFIL, DATACADASTRO, ATIVO)
VALUES ('Administrador','admin@disastereye.com',
        '$2a$11$xK8iMhMhvjv6gW9pWzT5e.aXm4oR3fHkLnYqB2cSdPeJtNwMuOvAi',
        'Administrador', TO_TIMESTAMP('2025-01-01','YYYY-MM-DD'), 1);

-- ── Seed: Tecnologias ────────────────────────────────────────────
INSERT INTO TECNOLOGIAS (NOME,DESCRICAO,ORIGEMESPACIAL,LATITUDE,LONGITUDE,STATUS,DATACADASTRO,CATEGORIAIMPACTOID)
VALUES ('EONET Fire Tracker','Rastreamento de incêndios usando a API EONET da NASA com coordenadas de satélite.','NASA EONET',-15.78,-47.93,'Ativo',TO_TIMESTAMP('2025-01-01','YYYY-MM-DD'),1);

INSERT INTO TECNOLOGIAS (NOME,DESCRICAO,ORIGEMESPACIAL,LATITUDE,LONGITUDE,STATUS,DATACADASTRO,CATEGORIAIMPACTOID)
VALUES ('Sentinel Flood Monitor','Monitoramento de inundações por imagens SAR do satélite Sentinel-1 da ESA.','ESA Sentinel-1',-23.55,-46.63,'Monitorando',TO_TIMESTAMP('2025-01-01','YYYY-MM-DD'),2);

INSERT INTO TECNOLOGIAS (NOME,DESCRICAO,ORIGEMESPACIAL,LATITUDE,LONGITUDE,STATUS,DATACADASTRO,CATEGORIAIMPACTOID)
VALUES ('GPS Seismic Array','Rede de sensores sísmicos derivados de GPS espacial para detecção de terremotos.','GPS/GNSS Satellites',-3.10,-60.02,'Alerta',TO_TIMESTAMP('2025-01-01','YYYY-MM-DD'),3);

INSERT INTO TECNOLOGIAS (NOME,DESCRICAO,ORIGEMESPACIAL,LATITUDE,LONGITUDE,STATUS,DATACADASTRO,CATEGORIAIMPACTOID)
VALUES ('GOES-16 Storm Eye','Rastreamento de tempestades severas no Atlântico Sul via satélite GOES-16.','NOAA GOES-16',-10.00,-35.00,'Monitorando',TO_TIMESTAMP('2025-01-01','YYYY-MM-DD'),5);

INSERT INTO TECNOLOGIAS (NOME,DESCRICAO,ORIGEMESPACIAL,LATITUDE,LONGITUDE,STATUS,DATACADASTRO,CATEGORIAIMPACTOID)
VALUES ('Volcano SAR Monitor','Monitoramento de deformações vulcânicas via interferometria SAR Sentinel-2.','ESA Sentinel-2',-22.44,-45.85,'Ativo',TO_TIMESTAMP('2025-01-01','YYYY-MM-DD'),4);

COMMIT;

-- ── Views ────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW VW_TECNOLOGIAS_POR_CATEGORIA AS
SELECT c.NOME AS CATEGORIA, c.TIPODESASTRE, COUNT(t.ID) AS TOTAL
FROM CATEGORIASIMPACTO c
LEFT JOIN TECNOLOGIAS t ON t.CATEGORIAIMPACTOID = c.ID
GROUP BY c.NOME, c.TIPODESASTRE;
/

CREATE OR REPLACE VIEW VW_ESTATISTICAS_DASHBOARD AS
SELECT
    (SELECT COUNT(*)                       FROM TECNOLOGIAS)             AS TOTALTECNOLOGIAS,
    (SELECT COUNT(DISTINCT ORIGEMESPACIAL) FROM TECNOLOGIAS)             AS TOTALMISSOES,
    (SELECT COUNT(*)                       FROM CATEGORIASIMPACTO)       AS TOTALSETORES,
    (SELECT COUNT(*) FROM TECNOLOGIAS WHERE STATUS IN ('Alerta','Crítico')) AS ALERTASATIVOS
FROM DUAL;
/

-- ── Verificação ──────────────────────────────────────────────────
SELECT 'CATEGORIASIMPACTO' AS TABELA, COUNT(*) AS REGISTROS FROM CATEGORIASIMPACTO
UNION ALL SELECT 'USUARIOS',    COUNT(*) FROM USUARIOS
UNION ALL SELECT 'TECNOLOGIAS', COUNT(*) FROM TECNOLOGIAS;
